# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Andi van Onselen
email: andrea.vanonselen@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer & UX Designer creating user-centered solutions that bridge design and technology. Explore my portfolio showcasing web development, UX design, and problem-solving expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.andreafolgado.com" # the base hostname & protocol for your site

github_username:  CardinisCode
linkedin_username: acfolgado

# Social media links for footer
social:
  - title: envelope
    url: mailto:andrea.vanonselen@icloud.com
  - title: github
    url: https://github.com/CardinisCode
  - title: linkedin
    url: https://linkedin.com/in/acfolgado

# SEO Configuration
author:
  name: Andrea van Onselen (nee Folgado)
  email: andrea.vanonselen@icloud.com
  twitter: # Add your Twitter handle if you have one
  github: CardinisCode
  linkedin: acfolgado

# SEO Settings
seo:
  type: Person
  name: Andrea van Onselen (nee Folgado)
  description: Software Engineer & UX Designer
  url: https://www.andreafolgado.com
  image: /img/logos/personalised_logo/andi_logo_favicon.png
  google_site_verification: googlef23d9d5ee9194eb5.html

# Analytics (add your tracking ID when available)
google_analytics: G-H7TF1SFW4W

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - planning/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


